### ISSUE TITLE
ValueError: Found array with 0 sample(s) (shape=(0,)) while a minimum of 1 is required.

### ISSUE THREAD

**Issue by mrunal-byt** [selimsef/dfdc_deepfake_challenge#19]
./train.sh path/to/data num-of-gpus
100%██████████████████████████████████████████████████████████████████████████████████| 2765/2765 [06:11<00:00,  7.45it/s]
Traceback (most recent call last):
  File "training/pipelines/train_classifier.py", line 363, in <module>
    main()
  File "training/pipelines/train_classifier.py", line 227, in main
    summary_writer=summary_writer)
  File "training/pipelines/train_classifier.py", line 235, in evaluate_val
    bce, probs, targets = validate(model, data_loader=data_val)
  File "training/pipelines/train_classifier.py", line 290, in validate
    real_loss = log_loss(y[real_idx], x[real_idx], labels=[0, 1])
  File "/opt/conda/lib/python3.7/site-packages/sklearn/utils/validation.py", line 72, in inner_f
    return f(**kwargs)
  File "/opt/conda/lib/python3.7/site-packages/sklearn/metrics/_classification.py", line 2186, in log_loss
    y_pred = check_array(y_pred, ensure_2d=False)
  File "/opt/conda/lib/python3.7/site-packages/sklearn/utils/validation.py", line 72, in inner_f
    return f(**kwargs)
  File "/opt/conda/lib/python3.7/site-packages/sklearn/utils/validation.py", line 653, in check_array
    context))
ValueError: Found array with 0 sample(s) (shape=(0,)) while a minimum of 1 is required.

**Comment by selimsef** [comment]
Hi, something is wrong with your validation, seems like it has 0 samples
